### ISSUE TITLE
Signal init improvements

### ISSUE THREAD

**Issue by ryanpdwyer** [JohnMarohn/FreqDemod#6]
Two things I think should change:

1. The ability to use a completely temporary, in-memory hdf5 file, by setting `backing_store=False`.
2. The current init routine completely overwrites the filename that is passed to it, without any warning, and without any option to change this behavior. I think this is currently done because otherwise any of the created files (caused by previously running code / tests) would cause errors trying to run the tests / code again.
3. Might make sense to combine `open` method with init; `open` is really just initializing, but with an existing file rather than write-only.

I think if the default behavior is to create an entirely in-memory hdf5 file, these problems go away. I'll try out something on a branch in my repository.

**Comment by ryanpdwyer** [comment]
Current use cases appear to be:

1. Data from a numpy array, in-memory only hdf5
    - `backing_store=False`, filename irrelevant, `data, data_name, data_unit, dt` required)
2. Data from a numpy array, result stored to disk
    - `backing_store=True`, filename required (currently overwrites existing filename, could see both overwrite / don't overwrite being useful), `data, data_name, data_unit, dt` required
3. Read data from an hdf5 file: currently *do* save any changes, back to the same file, but difficult to make changes, because errors raised if the dataset already exists (can't rerun filters, etc with slightly different settings).

Potential other use cases:

4. Read data from an hdf5 file, do workup entirely in memory
    - `backing_store=False`, filename not required, (but open filename needs to be distinct from Signal filename)
5. Read data from an hdf5 file, save data + workup to another hdf5 file
    - `backing_store=True`, filename required, Signal.filename distinct from open filename

**Comment by JohnMarohn** [comment]
Regarding 2 in the second list — great idea.  I more and more like the idea of saving the worked-up data (phase vs time, freq vs time, etc) to a completely separate file entirely.  This keeps the data off limits.  One option would be to copy over the original x vs y data into the new file.

Another nice feature would be to be able to choose which datasets to save.  With the GUI, it’s nice to see the various windows and filters, but you don’t need to save them for posterity.  They occupy a LOT of space, I found working with Sarah’s mound of data this week.

Best Regards,
JM

On Jul 18, 2015, at 11:14 AM, ryanpdwyer <notifications@github.com<mailto:notifications@github.com>> wrote:


Current use cases appear to be:

  1.  Data from a numpy array, in-memory only hdf5
     *   backing_store=False, filename irrelevant, data, data_name, data_unit, dt required)
  2.  Data from a numpy array, result stored to disk
     *   backing_store=True, filename required (currently overwrites existing filename, could see both overwrite / don't overwrite being useful), data, data_name, data_unit, dt required
  3.  Read data from an hdf5 file: currently do save any changes, back to the same file, but difficult to make changes, because errors raised if the dataset already exists (can't rerun filters, etc with slightly different settings).

Potential other use cases:

  1.  Read data from an hdf5 file, do workup entirely in memory
     *   backing_store=False, filename not required, (but open filename needs to be distinct from Signal filename)
  2.  Read data from an hdf5 file, save data + workup to another hdf5 file
     *   backing_store=True, filename required, Signal.filename distinct from open filename

**Comment by ryanpdwyer** [comment]
Changing the default initialization is not causing the problems I've feared, since h5py sensibly doesn't  treat a purely in memory file (`driver='core', backing_store=False`) the same as an actual file with the same name. I have a version of some `load_hdf5` routines, plus an init routine defaulting to in-memory in the `signal-init-load-hdf5` branch.

I tried running the new code on some old data workups; the only issues are caused in a few places where a Signal is created, numpy_array loaded, closed, then a new Signal is created, which opens the previously created file. It was easily fixed by specifying `backing_store=True` in those cases,
